import { SharePage } from '@/components/home/share-page/SharePage'
import { PostService } from '@/services/post-service/post-service'
import { Metadata } from 'next'
import { TOTAL_PAGES } from '@/constants/pagination.constants'

export const metadata: Metadata = {
  title: 'posts',
  description: 'Generated by create next app',
}

export default async function HomePage() {
  let posts = await PostService.getAllPosts()
  posts = posts.slice(0, TOTAL_PAGES)

  return <SharePage posts={posts} />
}
